### ISSUE TITLE
Issue with "Sample Policies" in @site/docs/policy_samples.mdx

### ISSUE THREAD

**Issue by MPH13** [PaloAltoNetworks/cortex.pan.dev#53]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

Privileged is spelled incorrectly
"Deny Privilaged Pod#
https://prisma.pan.dev/docs/policy_samples#deny-privilaged-pod

## Suggested fix
Proper spelling:
Privileged

**Comment by sserrata** [comment]
@csestito Can you ensure that this issue is addressed on the prisma site?
